'use strict';

const pkg = require('../../package.json');
const VERSION_STAMP = `<!-- copilotforge: v${pkg.version} -->`;

const IMPLEMENTATION_PLAN_MD = `# Implementation Plan
#
# Generated by CopilotForge. This file drives the Ralph Loop — an autonomous
# dev pattern where an AI works through your tasks one by one.
#
# HOW IT WORKS:
#   1. Describe your tasks below (one per line)
#   2. Run the task-loop recipe: npx ts-node cookbook/task-loop.ts
#   3. Ralph picks the next [ ] task, implements it, validates, commits, repeats
#
# TASK FORMAT:
#   - [ ] task-id — Task description (pending)
#   - [x] task-id — Task description (done — Ralph marks these)
#   - [!] task-id — Task description (failed — Ralph marks these)
#
# TIP: Run the CopilotForge wizard ("set up my project") with Task Automation
# enabled to auto-generate tasks from your project description.

- [ ] setup-project — Initialize project structure and dependencies
- [ ] hello-world — Create a minimal working example
- [ ] add-tests — Add basic test coverage
`;

const GETTING_STARTED_MD = `# Getting Started with CopilotForge

> Your project has been scaffolded! Here's what to do next.

## What was created

| File | Purpose |
|------|---------|
| \`.github/skills/planner/SKILL.md\` | The wizard skill — teaches your AI assistant how to set up projects |
| \`.github/skills/planner/reference.md\` | Reference material for the planner |
| \`FORGE.md\` | Your project's control panel — edit this to change what Copilot knows |
| \`.copilot/agents/planner.md\` | Planner agent definition |
| \`forge-memory/decisions.md\` | Architecture decision log |
| \`forge-memory/patterns.md\` | Coding conventions and patterns |
| \`forge-memory/preferences.md\` | Your preferences for CopilotForge behavior |
| \`cookbook/hello-world.ts\` | Starter recipe (TypeScript) |
| \`cookbook/hello-world.py\` | Starter recipe (Python) |

## Quickstart (3 steps)

1. **Open your AI assistant** — GitHub Copilot Chat, Claude Code, or any tool that reads \`.github/skills/\`
2. **Say: "set up my project"** — the planner wizard will start
3. **Answer a few questions** — describe your project, stack, and preferences

That's it! Your AI assistant generates skills, agents, and recipes customized for your stack.

## Learn more

- [Full documentation](https://github.com/Bradliebs/CopilotForge)
- [Examples](https://github.com/Bradliebs/CopilotForge/tree/main/examples)
- [Cookbook recipes](https://github.com/Bradliebs/CopilotForge/tree/main/cookbook)

${VERSION_STAMP}
`;

const DEVCONTAINER_JSON = JSON.stringify({
  name: 'CopilotForge Dev Container',
  image: 'mcr.microsoft.com/devcontainers/javascript-node:20',
  customizations: {
    vscode: {
      extensions: [
        'GitHub.copilot',
        'GitHub.copilot-chat',
        'dbaeumer.vscode-eslint',
        'esbenp.prettier-vscode',
      ],
    },
  },
  postCreateCommand: 'if [ -f package.json ]; then npm install; fi',
  remoteUser: 'node',
}, null, 2) + '\n';

const COPILOT_INSTRUCTIONS_MD = `# Copilot Instructions

Guidelines for AI assistants working in this project.

## Before You Write Code

- State your assumptions explicitly. If a request is ambiguous, ask — don't pick silently.
- If a simpler approach exists, say so before implementing the complex one.
- If something is unclear, stop and name what's confusing.

## Writing Code

- Minimum code that solves the problem. No features that weren't asked for.
- No abstractions for single-use code. No "flexibility" that wasn't requested.
- Match existing style and conventions in the file you're editing.
- Touch only what the request requires — don't improve adjacent code.

## After Writing Code

- Every changed line should trace directly to the request.
- If you made something unused with your changes, remove it.
- Don't remove pre-existing dead code unless asked.

## When in Doubt

Ask one focused question rather than making an assumption and writing 200 lines.
`;

const START_HERE_MD = `# Welcome to CopilotForge

CopilotForge added one file to your project:

**\`.github/skills/planner/SKILL.md\`** — This teaches your AI assistant how to set up skills for your project.

---

## Get started in 2 steps

**Step 1:** Open your AI chat window
- GitHub Copilot Chat → the speech-bubble icon in VS Code's left sidebar
- Or Claude Code, Cursor, or any AI that can read your project files

**Step 2:** Type this:
> set up my project

Your AI will ask three quick questions (what you're building, your stack, your experience level) then create custom skills for your project. Takes about one minute.

---

## What you'll have after the wizard runs

- \`.github/skills/code-review/SKILL.md\` — say **"review this code"** to use it
- \`.github/skills/test-helper/SKILL.md\` — say **"write tests for this"** to use it
- \`cookbook/starter.{ext}\` — a working code example to build from

---

## You can't break anything

All of these files are plain text. If something looks wrong, just delete the file and run \`npx copilotforge init\` again.

Need the full setup (memory system, agents, advanced recipes)?
Run \`npx copilotforge init --full\`

Questions? → https://github.com/Bradliebs/CopilotForge/discussions

${VERSION_STAMP}
`;

// Note: devcontainer.json for Codespaces is also deployed via init.js FULL_FILES
module.exports = { IMPLEMENTATION_PLAN_MD, GETTING_STARTED_MD, DEVCONTAINER_JSON, START_HERE_MD, COPILOT_INSTRUCTIONS_MD };