'use strict';

const pkg = require('../../package.json');
const VERSION_STAMP = `<!-- copilotforge: v${pkg.version} -->`;

const IMPLEMENTATION_PLAN_MD = `# Implementation Plan
#
# Generated by CopilotForge. This file drives the Ralph Loop — an autonomous
# dev pattern where an AI works through your tasks one by one.
#
# HOW IT WORKS:
#   1. Describe your tasks below (one per line)
#   2. Run the task-loop recipe: npx ts-node cookbook/task-loop.ts
#   3. Ralph picks the next [ ] task, implements it, validates, commits, repeats
#
# TASK FORMAT:
#   - [ ] task-id — Task description (pending)
#   - [x] task-id — Task description (done — Ralph marks these)
#   - [!] task-id — Task description (failed — Ralph marks these)
#
# TIP: Run the CopilotForge wizard ("set up my project") with Task Automation
# enabled to auto-generate tasks from your project description.

- [ ] setup-project — Initialize project structure and dependencies
- [ ] hello-world — Create a minimal working example
- [ ] add-tests — Add basic test coverage
`;

const GETTING_STARTED_MD = `# Getting Started with CopilotForge

> Your project has been scaffolded! Here's what to do next.

## What was created

| File | Purpose |
|------|---------|
| \`.github/skills/planner/SKILL.md\` | The wizard skill — teaches your AI assistant how to set up projects |
| \`.github/skills/planner/reference.md\` | Reference material for the planner |
| \`FORGE.md\` | Your project's control panel — edit this to change what Copilot knows |
| \`.copilot/agents/planner.md\` | Planner agent definition |
| \`forge-memory/decisions.md\` | Architecture decision log |
| \`forge-memory/patterns.md\` | Coding conventions and patterns |
| \`forge-memory/preferences.md\` | Your preferences for CopilotForge behavior |
| \`cookbook/hello-world.ts\` | Starter recipe (TypeScript) |
| \`cookbook/hello-world.py\` | Starter recipe (Python) |

## Quickstart (3 steps)

1. **Open your AI assistant** — GitHub Copilot Chat, Claude Code, or any tool that reads \`.github/skills/\`
2. **Say: "set up my project"** — the planner wizard will start
3. **Answer a few questions** — describe your project, stack, and preferences

That's it! Your AI assistant generates skills, agents, and recipes customized for your stack.

## Learn more

- [Full documentation](https://github.com/Bradliebs/CopilotForge)
- [Examples](https://github.com/Bradliebs/CopilotForge/tree/main/examples)
- [Cookbook recipes](https://github.com/Bradliebs/CopilotForge/tree/main/cookbook)

${VERSION_STAMP}
`;

module.exports = { IMPLEMENTATION_PLAN_MD, GETTING_STARTED_MD };