/**
 * skill-creation-example.ts — CopilotForge Cookbook Recipe
 *
 * WHAT THIS DOES:
 *   Demonstrates how to programmatically create a custom SKILL.md file
 *   that follows CopilotForge conventions. Useful for teams that want to
 *   generate skills from config files, CI pipelines, or custom tooling.
 *
 * WHEN TO USE THIS:
 *   When you want to create skills outside the wizard — e.g., generating
 *   skills from an OpenAPI spec, a database schema, or a team runbook.
 *
 * HOW TO RUN:
 *   1. npm install
 *   2. npx ts-node cookbook/skill-creation-example.ts
 *
 * PREREQUISITES:
 *   - Node.js 18+
 *   - TypeScript 5+
 *
 * PLATFORM NOTES:
 *   - Windows: Use backslashes in paths or path.join() (both shown in code)
 *   - macOS/Linux: Forward slashes work natively
 *   - Environment variables: Use $env:VAR (PowerShell) or export VAR (bash)
 */

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

// --- Types ---

/** Definition of a single trigger phrase. */
interface Trigger {
  phrase: string;
  description?: string;
}

/** A pattern within a skill — a reusable convention. */
interface SkillPattern {
  name: string;
  description: string;
  example?: string;
}

/** An anti-pattern — something to avoid. */
interface AntiPattern {
  description: string;
  reason: string;
}

/** Full definition of a skill. */
interface SkillDefinition {
  name: string;
  description: string;
  domain: string;
  confidence: "high" | "medium" | "low";
  triggers: Trigger[];
  context: string;
  instructions: string[];
  patterns: SkillPattern[];
  antiPatterns: AntiPattern[];
}

// --- Skill Builder ---

/**
 * Builds a SKILL.md string from a SkillDefinition.
 * Follows the CopilotForge format: YAML frontmatter + markdown sections.
 */
function buildSkillMarkdown(skill: SkillDefinition): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push("---");
  lines.push(`name: "${skill.name}"`);
  lines.push(`description: "${skill.description}"`);
  lines.push(`domain: "${skill.domain}"`);
  lines.push(`confidence: "${skill.confidence}"`);
  lines.push(`source: "generated by CopilotForge"`);
  lines.push("triggers:");
  for (const trigger of skill.triggers) {
    lines.push(`  - "${trigger.phrase}"`);
  }
  lines.push("---");
  lines.push("");

  // Title
  lines.push(`# ${skill.name}`);
  lines.push("");

  // Context
  lines.push("## Context");
  lines.push("");
  lines.push(skill.context);
  lines.push("");

  // Instructions
  lines.push("## Instructions");
  lines.push("");
  for (let i = 0; i < skill.instructions.length; i++) {
    lines.push(`${i + 1}. ${skill.instructions[i]}`);
  }
  lines.push("");

  // Patterns
  lines.push("## Patterns");
  lines.push("");
  for (const pattern of skill.patterns) {
    lines.push(`### ${pattern.name}`);
    lines.push("");
    lines.push(pattern.description);
    if (pattern.example) {
      lines.push("");
      lines.push("```");
      lines.push(pattern.example);
      lines.push("```");
    }
    lines.push("");
  }

  // Anti-Patterns
  lines.push("## Anti-Patterns");
  lines.push("");
  for (const ap of skill.antiPatterns) {
    lines.push(`- ${ap.description} — ${ap.reason}`);
  }
  lines.push("");

  return lines.join("\n");
}

/**
 * Writes a SKILL.md to the correct directory.
 * Creates the directory if it doesn't exist.
 * Skips if the file already exists (safe for re-runs).
 */
function writeSkill(
  skill: SkillDefinition,
  targetDir: string
): { path: string; action: "created" | "skipped" } {
  const skillDir = join(targetDir, ".github", "skills", skill.name);
  const skillPath = join(skillDir, "SKILL.md");

  if (existsSync(skillPath)) {
    console.log(`[skip] ${skillPath} already exists`);
    return { path: skillPath, action: "skipped" };
  }

  mkdirSync(skillDir, { recursive: true });
  writeFileSync(skillPath, buildSkillMarkdown(skill), "utf-8");
  console.log(`[created] ${skillPath}`);
  return { path: skillPath, action: "created" };
}

// --- Example Usage ---

async function main() {
  // Example: Create a custom "deployment" skill programmatically.
  const deploymentSkill: SkillDefinition = {
    name: "deployment",
    description: "Guides safe deployment to staging and production environments",
    domain: "devops",
    confidence: "medium",
    triggers: [
      { phrase: "deploy to staging" },
      { phrase: "deploy to production" },
      { phrase: "release this" },
      { phrase: "ship it" },
    ],
    context:
      "This skill handles deployment workflows. It ensures pre-deployment checks " +
      "are complete, the correct environment is targeted, and rollback procedures " +
      "are documented before any deployment begins.",
    instructions: [
      "Confirm the target environment (staging or production).",
      "Run pre-deployment checks: tests pass, no lint errors, changelog updated.",
      "If deploying to production, require explicit confirmation.",
      "Execute the deployment command for the target environment.",
      "Verify the deployment succeeded (health check, smoke test).",
      "Record the deployment in forge-memory/decisions.md.",
    ],
    patterns: [
      {
        name: "Pre-Deploy Checklist",
        description: "Always verify these before deploying:",
        example:
          "- [ ] All tests pass\n- [ ] No lint errors\n- [ ] Changelog updated\n- [ ] Version bumped",
      },
      {
        name: "Rollback Plan",
        description:
          "Every deployment must have a rollback plan documented before execution. " +
          "Include the previous version number and the rollback command.",
        example: 'Previous version: 1.2.3\nRollback: git revert HEAD && npm run deploy:staging',
      },
    ],
    antiPatterns: [
      {
        description: "Deploying without running tests",
        reason: "Untested code in production causes outages.",
      },
      {
        description: "Deploying to production without staging first",
        reason: "Staging catches environment-specific bugs before they hit users.",
      },
      {
        description: "No rollback plan",
        reason: "If deployment fails, you need to recover fast — not figure it out under pressure.",
      },
    ],
  };

  // Write to the current directory.
  const result = writeSkill(deploymentSkill, process.cwd());
  console.log(`\nResult: ${result.action} at ${result.path}`);

  // Example: Create another skill from a simpler definition.
  const loggingSkill: SkillDefinition = {
    name: "logging-conventions",
    description: "Structured logging patterns for consistent observability",
    domain: "observability",
    confidence: "medium",
    triggers: [
      { phrase: "add logging" },
      { phrase: "logging conventions" },
      { phrase: "structured logs" },
    ],
    context:
      "This skill defines how the project handles logging. All log output must be " +
      "structured (JSON), include correlation IDs, and follow severity levels.",
    instructions: [
      "Use structured JSON logging — never bare console.log in production code.",
      "Include a correlation ID in every log entry for request tracing.",
      "Use severity levels consistently: debug, info, warn, error.",
      "Log at function boundaries: entry (debug), exit (debug), errors (error).",
    ],
    patterns: [
      {
        name: "Structured Log Entry",
        description: "Every log entry follows this shape:",
        example:
          '{ "level": "info", "message": "User created", "correlationId": "abc-123", "userId": "u-456", "timestamp": "2025-01-15T10:30:00Z" }',
      },
    ],
    antiPatterns: [
      {
        description: "Using console.log in production",
        reason: "Unstructured logs are impossible to search and filter at scale.",
      },
      {
        description: "Logging sensitive data (passwords, tokens)",
        reason: "Logs are often stored in plain text and accessible to many people.",
      },
    ],
  };

  const result2 = writeSkill(loggingSkill, process.cwd());
  console.log(`Result: ${result2.action} at ${result2.path}`);
}

main().catch(console.error);
