'use strict';

// Embedded templates for default scaffold mode.
// These are starter files; the wizard replaces placeholders with real values.

const FORGE_MD = `<!-- FORGE.md — Generated by CopilotForge -->
<!-- This is your project's control panel. Edit it to change what Copilot knows about your project. -->

# \uD83D\uDD28 FORGE.md

> **Run the wizard to fill this in.** Open Copilot Chat and say "set up my project".

---

## Project Summary

| Field | Value |
|-------|-------|
| **Name** | (your project) |
| **Description** | (one-sentence summary) |
| **Stack** | (languages, frameworks, tools) |
| **Created** | (date) |
| **Forged by** | CopilotForge |

---

## Team Roster

Agents live in \`.copilot/agents/\` and handle different aspects of your project.

| Agent | Role | File |
|-------|------|------|
| Planner | Orchestrator — runs the wizard | \`.copilot/agents/planner.md\` |

> Say "set up my project" in Copilot Chat to generate agents for your stack.

---

## Skills Index

Skills live in \`.github/skills/\` and teach agents how to handle specific triggers.

| Skill | Trigger | Description |
|-------|---------|-------------|
| planner | "set up my project" | Guided project scaffolding wizard |

---

## Cookbook

Recipes live in \`cookbook/\` and provide copy-paste code patterns.

| Recipe | Language | Description |
|--------|----------|-------------|
| hello-world | TS / PY | Minimal Copilot SDK example |

> Say "set up my project" to generate recipes tailored to your stack.
`;

const PLANNER_AGENT_MD = `# Planner — Wizard Orchestrator

## Role
Run the CopilotForge intake wizard, generate all project scaffolding, and deliver a complete Copilot-ready repo structure from a plain-English description.

## Scope
- 6-question intake wizard (project, stack, memory, testing, skill level, extras)
- Skill definitions, agent configurations, memory files, and cookbook recipe generation
- FORGE.md generation (control panel)
- Validation summary (final report to user)

## System Prompt

You are the CopilotForge Planner. Load and follow \`.github/skills/planner/SKILL.md\` as your core protocol.

### Workflow
1. Read any existing memory in \`forge-memory/\`
2. Ask 6 questions (project, stack, memory prefs, testing prefs, skill level, extras)
3. Confirm answers with user
4. Generate all scaffolding files
5. Print validation summary
`;

const DECISIONS_MD = `# Decisions

Architecture and design decisions for this project.

| Date | Decision | Rationale |
|------|----------|-----------|
| | | |
`;

const PATTERNS_MD = `# Patterns

Coding conventions and patterns used in this project.

## Naming

(Describe your naming conventions here)

## File Structure

(Describe your file organization here)

## Code Style

(Describe your code style preferences here)
`;

const PREFERENCES_MD = `# Preferences

User preferences for CopilotForge behavior.

| Preference | Value |
|------------|-------|
| Verbosity | normal |
| Auto-commit | false |
| Test framework | (auto-detect) |
`;

const HELLO_WORLD_TS = `/**
 * hello-world.ts — CopilotForge Cookbook Recipe (Starter)
 *
 * A minimal starter recipe showing the pattern for Copilot SDK usage.
 * Run the wizard ("set up my project") to generate recipes for your stack.
 */

async function main(): Promise<void> {
  console.log('[CopilotForge] Hello, world!');
  console.log('[CopilotForge] Run the wizard to generate real recipes for your project.');
  console.log('[CopilotForge] Open Copilot Chat and say: "set up my project"');
}

main().catch(console.error);
`;

const HELLO_WORLD_PY = `"""
hello-world.py — CopilotForge Cookbook Recipe (Starter)

A minimal starter recipe showing the pattern for Copilot SDK usage.
Run the wizard ("set up my project") to generate recipes for your stack.
"""


def main() -> None:
    print("[CopilotForge] Hello, world!")
    print("[CopilotForge] Run the wizard to generate real recipes for your project.")
    print('[CopilotForge] Open Copilot Chat and say: "set up my project"')


if __name__ == "__main__":
    main()
`;

const TASK_LOOP_TS = `/**
 * task-loop.ts — CopilotForge Cookbook Recipe
 *
 * WHAT THIS DOES:
 *   Implements the autonomous dev loop pattern (Ralph Loop): read a plan
 *   from disk, pick the next pending task, implement it, validate the result,
 *   mark it done (with git commit) or failed, and repeat. State lives on
 *   disk — not in memory — so each iteration starts with fresh context.
 *
 * HARDENED FEATURES (Squad-inspired):
 *   - Safe git staging: stages only specific files, never \`git add -A\`
 *   - Graceful shutdown: check \`.forge-stop\` file or FORGE_STOP env var
 *   - 4-tier error escalation: retry → skip → pause → halt
 *   - Health summary: printed on exit and appended to forge-memory/decisions.md
 *   - Checkpoint persistence: \`.forge-state.json\` survives interruptions
 *   - Configurable max iterations via FORGE_MAX_ITERATIONS env var
 *
 * WHEN TO USE THIS:
 *   When you want an agent to work through an implementation plan
 *   autonomously — picking tasks, writing code, validating, and committing
 *   without human intervention between steps.
 *
 * HOW TO RUN:
 *   1. Create an IMPLEMENTATION_PLAN.md in your project root (see format below)
 *   2. npx ts-node cookbook/task-loop.ts
 *
 * PREREQUISITES:
 *   - Node.js 18+
 *   - TypeScript 5+
 *   - git initialized in the project
 *   - An IMPLEMENTATION_PLAN.md file (format shown in code)
 *
 * EXPECTED OUTPUT:
 *   [Ralph] Loaded 3 tasks from IMPLEMENTATION_PLAN.md
 *   [Ralph] === Iteration 1/10 ===
 *   [Ralph] Picked task: add-utils — "Create utility helpers"
 *   [Ralph] Implementing: add-utils...
 *   [Ralph] Validating: add-utils...
 *   [Ralph] ✅ Task add-utils passed — committing.
 *   [Ralph] === Iteration 2/10 ===
 *   ...
 *   [Ralph] 🏁 All tasks complete. 3 done, 0 failed.
 *   [Ralph] ═══════════════════════════════════
 *   [Ralph] 📊 Health Summary
 *   [Ralph]   Done:    3
 *   [Ralph]   Failed:  0
 *   [Ralph]   Pending: 0
 *   [Ralph]   Time:    12.4s
 *   [Ralph]   Reason:  all tasks complete
 *   [Ralph] ═══════════════════════════════════
 *
 * PLATFORM NOTES:
 *   - Windows: Use backslashes in paths or path.join() (both shown in code)
 *   - macOS/Linux: Forward slashes work natively
 *   - Environment variables: Use \$env:VAR (PowerShell) or export VAR (bash)
 */

import { readFileSync, writeFileSync, appendFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

// --- Types ---

type TaskStatus = "pending" | "done" | "failed";

interface Task {
  id: string;
  title: string;
  status: TaskStatus;
}

// --- Plan Parser ---

/**
 * Parses IMPLEMENTATION_PLAN.md into a list of tasks.
 * Expected format — one task per line:
 *   - [ ] task-id — Task title
 *   - [x] task-id — Task title        (done)
 *   - [!] task-id — Task title        (failed)
 */
function parsePlan(filePath: string): Task[] {
  const content = readFileSync(filePath, "utf-8");
  const tasks: Task[] = [];

  for (const line of content.split("\\n")) {
    const match = line.match(/^- \\[(.)\\] (\\S+)\\s*—\\s*(.+)\$/);
    if (!match) continue;

    const [, marker, id, title] = match;
    let status: TaskStatus = "pending";
    if (marker === "x") status = "done";
    else if (marker === "!") status = "failed";

    tasks.push({ id, title: title.trim(), status });
  }

  return tasks;
}

/** Writes the task list back to IMPLEMENTATION_PLAN.md. */
function writePlan(filePath: string, tasks: Task[]): void {
  const lines = ["# Implementation Plan", ""];
  for (const task of tasks) {
    const marker = task.status === "done" ? "x" : task.status === "failed" ? "!" : " ";
    lines.push(\`- [\${marker}] \${task.id} — \${task.title}\`);
  }
  writeFileSync(filePath, lines.join("\\n") + "\\n", "utf-8");
}

// --- Implementation (simulated) ---

/**
 * Simulate implementing a task — creates or modifies a file.
 * TODO: Replace with actual Copilot SDK call to generate code.
 */
function implementTask(task: Task): void {
  const outDir = join(".", "src");
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  const filePath = join(outDir, \`\${task.id}.ts\`);
  const content = \`// Auto-generated for task: \${task.id}\\n// \${task.title}\\nexport {};\\n\`;
  writeFileSync(filePath, content, "utf-8");
  console.log(\`[Ralph] Implementing: \${task.id}...\`);
}

// --- Validation (simulated) ---

/**
 * Simulate validation — run tests or a build check.
 * TODO: Replace with actual validation (e.g., execSync("npm test")).
 */
function validateTask(task: Task): boolean {
  console.log(\`[Ralph] Validating: \${task.id}...\`);
  // Simulate: all tasks pass. Replace with real checks.
  return true;
}

// --- Git Helpers ---

function gitCommit(message: string, files: string[]): void {
  try {
    // Stage specific files only — NEVER git add -A
    for (const f of files) {
      execSync(\`git add "\${f}"\`, { stdio: "pipe" });
    }
    // Always stage the plan file
    execSync('git add "IMPLEMENTATION_PLAN.md"', { stdio: "pipe" });

    // Safety check: verify staged file count
    const staged = execSync("git diff --cached --name-only", { stdio: "pipe" }).toString().trim();
    const fileCount = staged ? staged.split("\\n").length : 0;
    if (fileCount > 20) {
      console.warn(\`[Ralph] ⚠️ WARNING: \${fileCount} files staged — this seems too many for one task. Aborting commit.\`);
      execSync("git reset HEAD", { stdio: "pipe" });
      return;
    }
    if (fileCount > 10) {
      console.warn(\`[Ralph] ⚠️ Note: \${fileCount} files staged — more than usual for a single task.\`);
    }

    execSync(\`git commit -m "\${message}"\`, { stdio: "pipe" });
  } catch {
    console.warn("[Ralph] Git commit skipped (no changes or git not configured).");
  }
}

// --- Graceful Shutdown ---

function shouldStop(): boolean {
  if (existsSync(".forge-stop")) {
    console.log("[Ralph] 🛑 Stop signal detected (.forge-stop file). Shutting down gracefully.");
    return true;
  }
  if (process.env.FORGE_STOP === "1" || process.env.FORGE_STOP === "true") {
    console.log("[Ralph] 🛑 Stop signal detected (FORGE_STOP env). Shutting down gracefully.");
    return true;
  }
  return false;
}

// --- Checkpoint Persistence ---

interface LoopState {
  iteration: number;
  startedAt: string;
  lastTaskId: string;
  totalDone: number;
  totalFailed: number;
}

function saveCheckpoint(state: LoopState): void {
  writeFileSync(".forge-state.json", JSON.stringify(state, null, 2), "utf-8");
}

function loadCheckpoint(): LoopState | null {
  if (!existsSync(".forge-state.json")) return null;
  try {
    return JSON.parse(readFileSync(".forge-state.json", "utf-8"));
  } catch {
    return null;
  }
}

// --- Health Summary ---

function writeHealthSummary(tasks: Task[], startTime: number, reason: string): void {
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  const done = tasks.filter((t) => t.status === "done").length;
  const failed = tasks.filter((t) => t.status === "failed").length;
  const pending = tasks.filter((t) => t.status === "pending").length;

  console.log();
  console.log("[Ralph] ═══════════════════════════════════");
  console.log("[Ralph] 📊 Health Summary");
  console.log(\`[Ralph]   Done:    \${done}\`);
  console.log(\`[Ralph]   Failed:  \${failed}\`);
  console.log(\`[Ralph]   Pending: \${pending}\`);
  console.log(\`[Ralph]   Time:    \${elapsed}s\`);
  console.log(\`[Ralph]   Reason:  \${reason}\`);
  console.log("[Ralph] ═══════════════════════════════════");

  // Write to forge-memory/decisions.md if it exists
  if (existsSync("forge-memory")) {
    const summary = \`\\n## Ralph Loop Run — \${new Date().toISOString()}\\n- Done: \${done}, Failed: \${failed}, Pending: \${pending}\\n- Time: \${elapsed}s\\n- Exit reason: \${reason}\\n\`;
    const decisionsPath = join(".", "forge-memory", "decisions.md");
    if (existsSync(decisionsPath)) {
      appendFileSync(decisionsPath, summary, "utf-8");
    }
  }
}

// --- Ralph Loop ---

function ralphLoop(planPath: string, maxIterations: number = 10): void {
  if (!existsSync(planPath)) {
    console.error(\`[Ralph] Plan not found: \${planPath}\`);
    console.error("[Ralph] Create an IMPLEMENTATION_PLAN.md with tasks like:");
    console.error("  - [ ] task-id — Task title");
    return;
  }

  const startTime = Date.now();
  let consecutiveFailures = 0;
  let totalFailures = 0;

  // Resume from checkpoint if available
  const checkpoint = loadCheckpoint();
  let iteration = checkpoint ? checkpoint.iteration : 0;
  if (checkpoint) {
    console.log(\`[Ralph] Resuming from checkpoint — iteration \${checkpoint.iteration}, last task: \${checkpoint.lastTaskId}\`);
  }

  while (iteration < maxIterations) {
    iteration++;

    // Graceful shutdown check
    if (shouldStop()) {
      const tasks = parsePlan(planPath);
      writeHealthSummary(tasks, startTime, "graceful shutdown requested");
      return;
    }

    // Fresh read from disk on every iteration (key principle).
    const tasks = parsePlan(planPath);

    if (iteration === 1 || (checkpoint && iteration === checkpoint.iteration + 1)) {
      console.log(\`[Ralph] Loaded \${tasks.length} tasks from \${planPath}\`);
    }

    const pending = tasks.find((t) => t.status === "pending");
    if (!pending) {
      const done = tasks.filter((t) => t.status === "done").length;
      const failed = tasks.filter((t) => t.status === "failed").length;
      console.log(\`[Ralph] 🏁 All tasks complete. \${done} done, \${failed} failed.\`);
      writeHealthSummary(tasks, startTime, "all tasks complete");
      return;
    }

    console.log(\`[Ralph] === Iteration \${iteration}/\${maxIterations} ===\`);
    console.log(\`[Ralph] Picked task: \${pending.id} — "\${pending.title}"\`);

    // Implement
    implementTask(pending);
    const implementedFile = join("src", \`\${pending.id}.ts\`);

    // Validate
    const passed = validateTask(pending);

    // Update status on disk
    const freshTasks = parsePlan(planPath);
    const target = freshTasks.find((t) => t.id === pending.id);
    if (target) {
      target.status = passed ? "done" : "failed";
      writePlan(planPath, freshTasks);
    }

    if (passed) {
      consecutiveFailures = 0;
      console.log(\`[Ralph] ✅ Task \${pending.id} passed — committing.\`);
      gitCommit(\`feat: \${pending.id} — \${pending.title}\`, [implementedFile]);
    } else {
      consecutiveFailures++;
      totalFailures++;
      console.log(\`[Ralph] ❌ Task \${pending.id} failed — marked as failed, continuing.\`);

      // Tier 3: Pause and warn after 3 consecutive failures
      if (consecutiveFailures >= 3) {
        console.warn("[Ralph] ⚠️ 3 consecutive failures — something may be wrong.");
        console.warn("[Ralph] Pausing for 10 seconds. Create .forge-stop to halt.");
        execSync('node -e "setTimeout(()=>{},10000)"', { stdio: "pipe" });
      }

      // Tier 4: Halt after 5 total failures
      if (totalFailures >= 5) {
        console.error("[Ralph] 🛑 5+ total failures — halting autonomous execution.");
        writeHealthSummary(freshTasks, startTime, "halted — too many failures");
        return;
      }
    }

    // Save checkpoint after each iteration
    saveCheckpoint({
      iteration,
      startedAt: new Date(startTime).toISOString(),
      lastTaskId: pending.id,
      totalDone: freshTasks.filter((t) => t.status === "done").length,
      totalFailed: freshTasks.filter((t) => t.status === "failed").length,
    });
  }

  const tasks = parsePlan(planPath);
  console.log(\`[Ralph] ⚠️ Reached max iterations (\${maxIterations}). Stopping.\`);
  writeHealthSummary(tasks, startTime, \`max iterations reached (\${maxIterations})\`);
}

// --- Entry Point ---

const maxIterations = parseInt(process.env.FORGE_MAX_ITERATIONS || "10", 10);
const planFile = join(".", "IMPLEMENTATION_PLAN.md");
ralphLoop(planFile, maxIterations);
`;

const TASK_LOOP_PY = `"""
task-loop.py — CopilotForge Cookbook Recipe

WHAT THIS DOES:
    Implements the autonomous dev loop pattern (Ralph Loop): read a plan
    from disk, pick the next pending task, implement it, validate the result,
    mark it done (with git commit) or failed, and repeat. State lives on
    disk — not in memory — so each iteration starts with fresh context.

HARDENED FEATURES (Squad-inspired):
    - Safe git staging: stages only specific files, never \`git add -A\`
    - Graceful shutdown: check \`.forge-stop\` file or FORGE_STOP env var
    - 4-tier error escalation: retry → skip → pause → halt
    - Health summary: printed on exit and appended to forge-memory/decisions.md
    - Checkpoint persistence: \`.forge-state.json\` survives interruptions
    - Configurable max iterations via FORGE_MAX_ITERATIONS env var

WHEN TO USE THIS:
    When you want an agent to work through an implementation plan
    autonomously — picking tasks, writing code, validating, and committing
    without human intervention between steps.

HOW TO RUN:
    1. Create an IMPLEMENTATION_PLAN.md in your project root (see format below)
    2. python cookbook/task-loop.py

PREREQUISITES:
    - Python 3.10+
    - git initialized in the project
    - An IMPLEMENTATION_PLAN.md file (format shown in code)

EXPECTED OUTPUT:
    [Ralph] Loaded 3 tasks from IMPLEMENTATION_PLAN.md
    [Ralph] === Iteration 1/10 ===
    [Ralph] Picked task: add-utils — "Create utility helpers"
    [Ralph] Implementing: add-utils...
    [Ralph] Validating: add-utils...
    [Ralph] ✅ Task add-utils passed — committing.
    [Ralph] === Iteration 2/10 ===
    ...
    [Ralph] 🏁 All tasks complete. 3 done, 0 failed.
    [Ralph] ═══════════════════════════════════
    [Ralph] 📊 Health Summary
    [Ralph]   Done:    3
    [Ralph]   Failed:  0
    [Ralph]   Pending: 0
    [Ralph]   Time:    12.4s
    [Ralph]   Reason:  all tasks complete
    [Ralph] ═══════════════════════════════════

PLATFORM NOTES:
    - Windows: Use backslashes in paths or os.path.join() (both shown in code)
    - macOS/Linux: Forward slashes work natively
    - Environment variables: Use \$env:VAR (PowerShell) or export VAR (bash)
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


# --- Types ---


@dataclass
class Task:
    """A single task from the implementation plan."""

    id: str
    title: str
    status: str  # "pending", "done", or "failed"


# --- Plan Parser ---


def parse_plan(file_path: Path) -> list[Task]:
    """
    Parse IMPLEMENTATION_PLAN.md into a list of tasks.
    Expected format — one task per line:
        - [ ] task-id — Task title
        - [x] task-id — Task title        (done)
        - [!] task-id — Task title        (failed)
    """
    content = file_path.read_text(encoding="utf-8")
    tasks: list[Task] = []

    for line in content.splitlines():
        match = re.match(r"^- \\[(.)\\] (\\S+)\\s*—\\s*(.+)\$", line)
        if not match:
            continue

        marker, task_id, title = match.group(1), match.group(2), match.group(3).strip()
        status = "pending"
        if marker == "x":
            status = "done"
        elif marker == "!":
            status = "failed"

        tasks.append(Task(id=task_id, title=title, status=status))

    return tasks


def write_plan(file_path: Path, tasks: list[Task]) -> None:
    """Write the task list back to IMPLEMENTATION_PLAN.md."""
    lines = ["# Implementation Plan", ""]
    for task in tasks:
        marker = {"done": "x", "failed": "!", "pending": " "}.get(task.status, " ")
        lines.append(f"- [{marker}] {task.id} — {task.title}")
    file_path.write_text("\\n".join(lines) + "\\n", encoding="utf-8")


# --- Implementation (simulated) ---


def implement_task(task: Task) -> None:
    """
    Simulate implementing a task — creates or modifies a file.
    TODO: Replace with actual Copilot SDK call to generate code.
    """
    out_dir = Path("src")
    out_dir.mkdir(parents=True, exist_ok=True)

    file_path = out_dir / f"{task.id}.py"
    content = f'# Auto-generated for task: {task.id}\\n# {task.title}\\n'
    file_path.write_text(content, encoding="utf-8")
    print(f"[Ralph] Implementing: {task.id}...")


# --- Validation (simulated) ---


def validate_task(task: Task) -> bool:
    """
    Simulate validation — run tests or a build check.
    TODO: Replace with actual validation (e.g., subprocess.run(["pytest"])).
    """
    print(f"[Ralph] Validating: {task.id}...")
    return True


# --- Git Helpers ---


def git_commit(message: str, files: list[str]) -> None:
    """Stage specific files and commit — NEVER git add -A."""
    try:
        for f in files:
            subprocess.run(["git", "add", f], capture_output=True, check=True)
        # Always stage the plan file
        subprocess.run(["git", "add", "IMPLEMENTATION_PLAN.md"], capture_output=True, check=True)

        # Safety check: verify staged file count
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True, text=True, check=True,
        )
        staged = result.stdout.strip()
        file_count = len(staged.splitlines()) if staged else 0
        if file_count > 20:
            print(f"[Ralph] ⚠️ WARNING: {file_count} files staged — this seems too many for one task. Aborting commit.")
            subprocess.run(["git", "reset", "HEAD"], capture_output=True, check=True)
            return
        if file_count > 10:
            print(f"[Ralph] ⚠️ Note: {file_count} files staged — more than usual for a single task.")

        subprocess.run(["git", "commit", "-m", message], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("[Ralph] Git commit skipped (no changes or git not configured).")


# --- Graceful Shutdown ---


def should_stop() -> bool:
    """Check for stop signals before each iteration."""
    if Path(".forge-stop").exists():
        print("[Ralph] 🛑 Stop signal detected (.forge-stop file). Shutting down gracefully.")
        return True
    if os.environ.get("FORGE_STOP") in ("1", "true"):
        print("[Ralph] 🛑 Stop signal detected (FORGE_STOP env). Shutting down gracefully.")
        return True
    return False


# --- Checkpoint Persistence ---


def save_checkpoint(state: dict) -> None:
    """Save loop state to .forge-state.json."""
    Path(".forge-state.json").write_text(json.dumps(state, indent=2), encoding="utf-8")


def load_checkpoint() -> dict | None:
    """Load loop state from .forge-state.json if it exists."""
    path = Path(".forge-state.json")
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


# --- Health Summary ---


def write_health_summary(tasks: list[Task], start_time: float, reason: str) -> None:
    """Print and optionally persist a summary of the loop run."""
    elapsed = f"{time.time() - start_time:.1f}"
    done = sum(1 for t in tasks if t.status == "done")
    failed = sum(1 for t in tasks if t.status == "failed")
    pending = sum(1 for t in tasks if t.status == "pending")

    print()
    print("[Ralph] ═══════════════════════════════════")
    print("[Ralph] 📊 Health Summary")
    print(f"[Ralph]   Done:    {done}")
    print(f"[Ralph]   Failed:  {failed}")
    print(f"[Ralph]   Pending: {pending}")
    print(f"[Ralph]   Time:    {elapsed}s")
    print(f"[Ralph]   Reason:  {reason}")
    print("[Ralph] ═══════════════════════════════════")

    # Write to forge-memory/decisions.md if it exists
    decisions_path = Path("forge-memory") / "decisions.md"
    if decisions_path.exists():
        summary = (
            f"\\n## Ralph Loop Run — {datetime.now(timezone.utc).isoformat()}\\n"
            f"- Done: {done}, Failed: {failed}, Pending: {pending}\\n"
            f"- Time: {elapsed}s\\n"
            f"- Exit reason: {reason}\\n"
        )
        with open(decisions_path, "a", encoding="utf-8") as f:
            f.write(summary)


# --- Ralph Loop ---


def ralph_loop(plan_path: Path, max_iterations: int = 10) -> None:
    """Main loop: pick task → implement → validate → commit → repeat."""
    if not plan_path.exists():
        print(f"[Ralph] Plan not found: {plan_path}")
        print("[Ralph] Create an IMPLEMENTATION_PLAN.md with tasks like:")
        print("  - [ ] task-id — Task title")
        return

    start_time = time.time()
    consecutive_failures = 0
    total_failures = 0

    # Resume from checkpoint if available
    checkpoint = load_checkpoint()
    iteration = checkpoint["iteration"] if checkpoint else 0
    if checkpoint:
        print(f"[Ralph] Resuming from checkpoint — iteration {checkpoint['iteration']}, last task: {checkpoint['lastTaskId']}")

    while iteration < max_iterations:
        iteration += 1

        # Graceful shutdown check
        if should_stop():
            tasks = parse_plan(plan_path)
            write_health_summary(tasks, start_time, "graceful shutdown requested")
            return

        # Fresh read from disk on every iteration (key principle).
        tasks = parse_plan(plan_path)

        if iteration == 1 or (checkpoint and iteration == checkpoint["iteration"] + 1):
            print(f"[Ralph] Loaded {len(tasks)} tasks from {plan_path}")

        pending = next((t for t in tasks if t.status == "pending"), None)
        if pending is None:
            done = sum(1 for t in tasks if t.status == "done")
            failed = sum(1 for t in tasks if t.status == "failed")
            print(f"[Ralph] 🏁 All tasks complete. {done} done, {failed} failed.")
            write_health_summary(tasks, start_time, "all tasks complete")
            return

        print(f"[Ralph] === Iteration {iteration}/{max_iterations} ===")
        print(f'[Ralph] Picked task: {pending.id} — "{pending.title}"')

        # Implement
        implement_task(pending)
        implemented_file = str(Path("src") / f"{pending.id}.py")

        # Validate
        passed = validate_task(pending)

        # Update status on disk
        fresh_tasks = parse_plan(plan_path)
        target = next((t for t in fresh_tasks if t.id == pending.id), None)
        if target:
            target.status = "done" if passed else "failed"
            write_plan(plan_path, fresh_tasks)

        if passed:
            consecutive_failures = 0
            print(f"[Ralph] ✅ Task {pending.id} passed — committing.")
            git_commit(f"feat: {pending.id} — {pending.title}", [implemented_file])
        else:
            consecutive_failures += 1
            total_failures += 1
            print(f"[Ralph] ❌ Task {pending.id} failed — marked as failed, continuing.")

            # Tier 3: Pause and warn after 3 consecutive failures
            if consecutive_failures >= 3:
                print("[Ralph] ⚠️ 3 consecutive failures — something may be wrong.")
                print("[Ralph] Pausing for 10 seconds. Create .forge-stop to halt.")
                time.sleep(10)

            # Tier 4: Halt after 5 total failures
            if total_failures >= 5:
                print("[Ralph] 🛑 5+ total failures — halting autonomous execution.")
                write_health_summary(fresh_tasks, start_time, "halted — too many failures")
                return

        # Save checkpoint after each iteration
        save_checkpoint({
            "iteration": iteration,
            "startedAt": datetime.fromtimestamp(start_time, tz=timezone.utc).isoformat(),
            "lastTaskId": pending.id,
            "totalDone": sum(1 for t in fresh_tasks if t.status == "done"),
            "totalFailed": sum(1 for t in fresh_tasks if t.status == "failed"),
        })

    tasks = parse_plan(plan_path)
    print(f"[Ralph] ⚠️ Reached max iterations ({max_iterations}). Stopping.")
    write_health_summary(tasks, start_time, f"max iterations reached ({max_iterations})")


# --- Entry Point ---

if __name__ == "__main__":
    plan_file = Path("IMPLEMENTATION_PLAN.md")
    max_iter = int(os.environ.get("FORGE_MAX_ITERATIONS", "10"))
    ralph_loop(plan_file, max_iter)
`;

const IMPLEMENTATION_PLAN_MD = `# Implementation Plan
#
# Generated by CopilotForge. This file drives the Ralph Loop — an autonomous
# dev pattern where an AI works through your tasks one by one.
#
# HOW IT WORKS:
#   1. Describe your tasks below (one per line)
#   2. Run the task-loop recipe: npx ts-node cookbook/task-loop.ts
#   3. Ralph picks the next [ ] task, implements it, validates, commits, repeats
#
# TASK FORMAT:
#   - [ ] task-id — Task description (pending)
#   - [x] task-id — Task description (done — Ralph marks these)
#   - [!] task-id — Task description (failed — Ralph marks these)
#
# TIP: Run the CopilotForge wizard ("set up my project") with Task Automation
# enabled to auto-generate tasks from your project description.

- [ ] setup-project — Initialize project structure and dependencies
- [ ] hello-world — Create a minimal working example
- [ ] add-tests — Add basic test coverage
`;

const GETTING_STARTED_MD = `# Getting Started with CopilotForge

> Your project has been scaffolded! Here's what to do next.

## What was created

| File | Purpose |
|------|---------|
| \`.github/skills/planner/SKILL.md\` | The wizard skill — teaches your AI assistant how to set up projects |
| \`.github/skills/planner/reference.md\` | Reference material for the planner |
| \`FORGE.md\` | Your project's control panel — edit this to change what Copilot knows |
| \`.copilot/agents/planner.md\` | Planner agent definition |
| \`forge-memory/decisions.md\` | Architecture decision log |
| \`forge-memory/patterns.md\` | Coding conventions and patterns |
| \`forge-memory/preferences.md\` | Your preferences for CopilotForge behavior |
| \`cookbook/hello-world.ts\` | Starter recipe (TypeScript) |
| \`cookbook/hello-world.py\` | Starter recipe (Python) |

## Quickstart (3 steps)

1. **Open your AI assistant** — GitHub Copilot Chat, Claude Code, or any tool that reads \`.github/skills/\`
2. **Say: "set up my project"** — the planner wizard will start
3. **Answer a few questions** — describe your project, stack, and preferences

That's it! Your AI assistant generates skills, agents, and recipes customized for your stack.

## Learn more

- [Full documentation](https://github.com/Bradliebs/CopilotForge)
- [Examples](https://github.com/Bradliebs/CopilotForge/tree/main/examples)
- [Cookbook recipes](https://github.com/Bradliebs/CopilotForge/tree/main/cookbook)
`;

const COPILOT_STUDIO_GUIDE_MD = `# 🏗️ Copilot Studio — Build Enterprise Agents from VS Code

> **What this does:** Walks you through building and managing Copilot Studio agents
> entirely from VS Code. Clone agents from the cloud, edit YAML locally, sync back.
>
> **When to use this:** When you want to build conversational or autonomous agents
> on Microsoft's enterprise platform with full version control.
>
> **Prerequisites:**
> - VS Code installed
> - [Copilot Studio extension](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.microsoft-copilot-studio) installed
> - Power Platform environment with Copilot Studio access
> - A Microsoft work or school account

---

## Step 1 — Install the Extension

1. Open VS Code
2. Go to Extensions (Ctrl+Shift+X)
3. Search for "Microsoft Copilot Studio"
4. Click **Install**

The extension adds agent-authoring capabilities directly in VS Code with YAML IntelliSense.

## Step 2 — Clone an Agent from Copilot Studio

1. Open the Command Palette (Ctrl+Shift+P)
2. Type "Copilot Studio: Clone Agent"
3. Sign in with your Power Platform account when prompted
4. Select the environment containing your agent
5. Choose the agent to clone

The agent's YAML definition downloads to your workspace. You'll see files like:
\`\`\`
my-agent/
├── agent.yaml          ← Main agent definition
├── topics/             ← Conversation flows
│   ├── greeting.yaml
│   └── fallback.yaml
├── tools/              ← External tool definitions
├── knowledge/          ← Knowledge sources
└── triggers/           ← What activates the agent
\`\`\`

## Step 3 — Edit Agent Components Locally

Edit any YAML file. The extension provides:
- **Syntax highlighting** for agent YAML
- **IntelliSense** — auto-complete for properties and values
- **Validation** — red squiggles for invalid configurations

### Example: Adding a new topic
Create a file in \`topics/\` with this structure:
\`\`\`yaml
kind: Topic
name: order-status
description: Handles customer order status inquiries
trigger:
  kind: Intent
  description: User asks about their order status
actions:
  - kind: Message
    text: "I can help you check your order status. What's your order number?"
\`\`\`

## Step 4 — Apply Changes to Copilot Studio

1. Open the Command Palette (Ctrl+Shift+P)
2. Type "Copilot Studio: Apply Changes"
3. Review the diff showing what will change
4. Confirm to push changes to your cloud environment

## Step 5 — Test Your Agent

1. Go to [Copilot Studio](https://copilotstudio.microsoft.com)
2. Open your agent
3. Click "Test" to try a conversation
4. Verify your changes work as expected

## Step 6 — Version Control with Git

Since agents are now local YAML files, you can:
\`\`\`bash
git add .
git commit -m "feat: add order-status topic"
git push origin main
\`\`\`

Use pull requests for team review of agent changes.

---

## Tips

- **Start by cloning an existing agent** rather than creating from scratch — it's easier to learn the YAML format by example.
- **Use GitHub Copilot or Claude Code** while editing YAML — they understand the Copilot Studio format and can suggest topics, tools, and triggers.
- **The extension syncs both ways** — you can clone (cloud → local) and apply (local → cloud).

## Learn More

- [Copilot Studio VS Code extension overview](https://learn.microsoft.com/microsoft-copilot-studio/visual-studio-code-extension-overview)
- [Edit agent components locally](https://learn.microsoft.com/microsoft-copilot-studio/visual-studio-code-extension-edit-agent-components)
- [Synchronize changes](https://learn.microsoft.com/microsoft-copilot-studio/visual-studio-code-extension-synchronization)
- [GitHub: microsoft/vscode-copilotstudio](https://github.com/microsoft/vscode-copilotstudio)
`;

const COPILOT_STUDIO_AGENT_YAML = `# copilot-studio-agent.yaml — CopilotForge Cookbook Example
#
# WHAT THIS IS:
#   An example Copilot Studio agent definition in YAML format.
#   This is what you'll see when you clone an agent from Copilot Studio
#   to your local VS Code workspace.
#
# HOW TO USE:
#   1. Install the Copilot Studio VS Code extension
#   2. Clone an agent (this gives you real YAML files like this one)
#   3. Edit the YAML locally — the extension provides IntelliSense
#   4. Apply changes back to Copilot Studio
#
# NOTE: This is a simplified example for learning. Real agent definitions
#       may have more properties. See the extension docs for the full schema.

kind: Agent
name: project-helper
description: A helpful assistant that answers questions about your project
language: en

# Knowledge sources — what the agent can reference
knowledge:
  - kind: File
    name: project-docs
    description: Project documentation and guides
    files:
      - README.md
      - docs/GETTING-STARTED.md

# Topics — conversation flows the agent can handle
topics:
  - kind: Topic
    name: greeting
    description: Welcome message when conversation starts
    trigger:
      kind: OnConversationStart
    actions:
      - kind: Message
        text: "Hi! I'm your project helper. I can answer questions about the project, explain how things work, or help you get started. What would you like to know?"

  - kind: Topic
    name: explain-architecture
    description: Explains the project architecture
    trigger:
      kind: Intent
      description: User asks about architecture or how the project is structured
    actions:
      - kind: Message
        text: "Let me look at the project docs and explain the architecture..."
      - kind: SearchKnowledge
        source: project-docs
      - kind: GenerateAnswer

  - kind: Topic
    name: fallback
    description: Handles unrecognized requests
    trigger:
      kind: OnUnknownIntent
    actions:
      - kind: Message
        text: "I'm not sure about that. Try asking about the project architecture, getting started, or specific features."

# Settings
settings:
  orchestrator:
    enabled: true
  generativeAI:
    enabled: true
`;

const CODE_APPS_GUIDE_MD = `# 💻 Code Apps — Build Power Apps with React & TypeScript

> **What this does:** Walks you through creating a Power App using React and
> TypeScript code instead of the traditional low-code canvas editor.
>
> **When to use this:** When you want the full power of a code IDE (VS Code)
> combined with Power Platform's data connectors and enterprise features.
>
> **Prerequisites:**
> - Node.js LTS (18+)
> - [Power Platform CLI](https://learn.microsoft.com/power-platform/developer/cli/introduction) (\`pac\`)
> - Power Platform environment with [code apps enabled](https://learn.microsoft.com/power-apps/developer/code-apps/overview#enable-code-apps-on-a-power-platform-environment)
> - A Microsoft work or school account

---

## Step 1 — Scaffold Your App

Open a terminal and run:

\`\`\`bash
npx degit github:microsoft/PowerAppsCodeApps/templates/vite my-app
cd my-app
\`\`\`

This creates a Vite-based React/TypeScript project pre-configured for Power Apps.

## Step 2 — Authenticate with Power Platform

\`\`\`bash
pac auth create
\`\`\`

Sign in with your Power Platform account when prompted. This connects your local tools to your cloud environment.

Then select your target environment:

\`\`\`bash
pac env select --environment <your-environment-id>
\`\`\`

> **How to find your environment ID:** Go to [Power Platform admin center](https://admin.powerplatform.microsoft.com), click your environment, and copy the ID from the URL.

## Step 3 — Install and Initialize

\`\`\`bash
npm install
pac code init --displayname "My First Code App"
\`\`\`

This:
- Installs the \`@microsoft/power-apps\` client library
- Creates a \`power.config.json\` file linking your app to Power Platform
- Sets up the connection between your code and the platform

## Step 4 — Run Locally

\`\`\`bash
npm run dev
\`\`\`

Open the **Local Play** URL shown in the terminal. Use the same browser profile as your Power Platform account.

> ⚠️ **Browser note:** Chrome and Edge may block localhost connections. If you see an error, grant permission for local network access in your browser settings.

## Step 5 — Build and Publish

When you're ready to deploy:

\`\`\`bash
npm run build | pac code push
\`\`\`

This compiles your React app and publishes it to Power Platform. You'll get a Power Apps URL to share with users.

## Step 6 — Connect to Data (Optional)

Code Apps can use Power Platform connectors for data. To add a connector:

\`\`\`bash
pac code add-connection --connector <connector-name>
\`\`\`

This generates TypeScript models and services in your project that you import and use like any other TypeScript module.

---

## Architecture Overview

\`\`\`
Your React/TypeScript Code
        ↓
Power Apps Client Library (@microsoft/power-apps)
        ↓
Power Platform Connectors (SharePoint, Dataverse, SQL, etc.)
        ↓
Data Sources
\`\`\`

The \`power.config.json\` file manages metadata. The client library handles authentication, connector access, and hosting integration. Your code stays as standard React/TypeScript.

## Tips

- **Start with the Vite template** — it has everything pre-configured.
- **Use \`npm run dev\` frequently** — hot reload works, so you see changes instantly.
- **Connectors give you enterprise data** — SharePoint lists, Dataverse tables, SQL databases, and 1000+ other sources, all with built-in auth.

## Learn More

- [Create a code app from scratch](https://learn.microsoft.com/power-apps/developer/code-apps/how-to/create-an-app-from-scratch)
- [Code apps architecture](https://learn.microsoft.com/power-apps/developer/code-apps/architecture)
- [System limits and configuration](https://learn.microsoft.com/power-apps/developer/code-apps/system-limits-configuration)
- [Connect your code app to data](https://learn.microsoft.com/power-apps/developer/code-apps/how-to/connect-to-data)
`;

const CODE_APPS_SETUP_TS = `/**
 * code-apps-setup.ts — CopilotForge Cookbook Recipe
 *
 * WHAT THIS DOES:
 *   Checks prerequisites for Power Apps Code Apps development and guides
 *   you through the initial setup. Verifies Node.js, PAC CLI, and
 *   Power Platform authentication are properly configured.
 *
 * WHEN TO USE THIS:
 *   Before starting your first Code App. Catches missing dependencies
 *   early so you don't hit errors mid-setup.
 *
 * HOW TO RUN:
 *   npx ts-node cookbook/code-apps-setup.ts
 *   Or: node cookbook/code-apps-setup.ts (if compiled)
 *
 * PREREQUISITES:
 *   - Node.js 18+
 *
 * EXPECTED OUTPUT:
 *   🔍 Code Apps Prerequisites Check
 *   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *   ✅ Node.js     v20.11.0 (LTS — good!)
 *   ✅ npm         v10.2.0
 *   ❌ PAC CLI     Not found — install: npm install -g @microsoft/pac-cli
 *   ⚠️  Auth       Run 'pac auth create' after installing PAC CLI
 *   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 */

import { execSync } from "node:child_process";

// --- ANSI helpers ---
const c = {
  reset: "\\x1b[0m",
  bold: "\\x1b[1m",
  dim: "\\x1b[2m",
  green: "\\x1b[32m",
  red: "\\x1b[31m",
  yellow: "\\x1b[33m",
  cyan: "\\x1b[36m",
};

const ok = \`\${c.green}✅\${c.reset}\`;
const fail = \`\${c.red}❌\${c.reset}\`;
const warn = \`\${c.yellow}⚠️\${c.reset}\`;
const line = "━".repeat(44);

interface CheckResult {
  label: string;
  status: "ok" | "fail" | "warn";
  detail: string;
}

function runCmd(cmd: string): string | null {
  try {
    return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
  } catch {
    return null;
  }
}

function checkNode(): CheckResult {
  const version = runCmd("node --version");
  if (!version) return { label: "Node.js", status: "fail", detail: "Not found — install from https://nodejs.org" };
  const major = parseInt(version.replace("v", "").split(".")[0], 10);
  if (major < 18) return { label: "Node.js", status: "warn", detail: \`\${version} (need 18+ LTS)\` };
  return { label: "Node.js", status: "ok", detail: \`\${version} (LTS — good!)\` };
}

function checkNpm(): CheckResult {
  const version = runCmd("npm --version");
  if (!version) return { label: "npm", status: "fail", detail: "Not found — comes with Node.js" };
  return { label: "npm", status: "ok", detail: \`v\${version}\` };
}

function checkPac(): CheckResult {
  const version = runCmd("pac --version");
  if (!version) return { label: "PAC CLI", status: "fail", detail: "Not found — install: dotnet tool install -g Microsoft.PowerApps.CLI.Tool" };
  return { label: "PAC CLI", status: "ok", detail: version };
}

function checkPacAuth(): CheckResult {
  const output = runCmd("pac auth list");
  if (!output) return { label: "Auth", status: "warn", detail: "Run 'pac auth create' to authenticate" };
  if (output.includes("No profiles")) return { label: "Auth", status: "warn", detail: "No auth profiles — run 'pac auth create'" };
  return { label: "Auth", status: "ok", detail: "Authenticated" };
}

function formatResult(r: CheckResult): string {
  const icon = r.status === "ok" ? ok : r.status === "fail" ? fail : warn;
  return \`  \${icon} \${r.label.padEnd(12)} \${c.dim}\${r.detail}\${c.reset}\`;
}

// --- Main ---
console.log(\`\\n  \${c.bold}🔍 Code Apps Prerequisites Check\${c.reset}\`);
console.log(\`  \${c.dim}\${line}\${c.reset}\`);

const checks = [checkNode(), checkNpm(), checkPac(), checkPacAuth()];
checks.forEach((r) => console.log(formatResult(r)));

console.log(\`  \${c.dim}\${line}\${c.reset}\`);

const failures = checks.filter((r) => r.status === "fail");
const warnings = checks.filter((r) => r.status === "warn");

if (failures.length === 0 && warnings.length === 0) {
  console.log(\`\\n  \${c.green}\${c.bold}All good!\${c.reset} You're ready to create a Code App.\`);
  console.log(\`  Run: \${c.cyan}npx degit github:microsoft/PowerAppsCodeApps/templates/vite my-app\${c.reset}\\n\`);
} else if (failures.length === 0) {
  console.log(\`\\n  \${c.yellow}\${c.bold}Almost there!\${c.reset} Fix the warnings above, then you're ready.\`);
  console.log(\`  Guide: \${c.cyan}cookbook/code-apps-guide.md\${c.reset}\\n\`);
} else {
  console.log(\`\\n  \${c.red}\${c.bold}Some things need fixing.\${c.reset} See the ❌ items above.\`);
  console.log(\`  Guide: \${c.cyan}cookbook/code-apps-guide.md\${c.reset}\\n\`);
}
`;

const COPILOT_AGENTS_GUIDE_MD = `# 🧩 Custom Agents — Create Specialized GitHub Copilot Profiles

> **What this does:** Walks you through creating custom agent profiles
> (\`.agent.md\` files) for GitHub Copilot. Each agent gets its own
> personality, tools, and expertise.
>
> **When to use this:** When you want specialized AI assistants for
> different tasks — a test writer, a code reviewer, a documentation
> expert, a security auditor — each with tailored instructions.
>
> **Prerequisites:**
> - GitHub Copilot subscription (Pro, Pro+, Business, or Enterprise)
> - VS Code with GitHub Copilot extension, or access to GitHub.com

---

## Step 1 — Create the Agents Directory

In your repository, create a \`.github/agents/\` directory:

\`\`\`bash
mkdir -p .github/agents
\`\`\`

This is where all your custom agent profiles live.

## Step 2 — Create an Agent Profile

Create a file with the pattern \`{name}.agent.md\`. For example, \`test-writer.agent.md\`:

\`\`\`bash
touch .github/agents/test-writer.agent.md
\`\`\`

> **Naming rules:** Filenames can only contain: \`.\`, \`-\`, \`_\`, \`a-z\`, \`A-Z\`, \`0-9\`

## Step 3 — Configure the YAML Frontmatter

Open the file and add YAML frontmatter at the top:

\`\`\`yaml
---
name: test-writer
description: Writes comprehensive tests with high coverage and clear descriptions
tools: ["read", "edit", "search", "shell"]
model: claude-sonnet-4
---
\`\`\`

**Properties explained:**
| Property | Required | What it does |
|----------|----------|--------------|
| \`name\` | No | Display name (defaults to filename) |
| \`description\` | **Yes** | What the agent does — Copilot uses this to decide when to suggest it |
| \`tools\` | No | Which tools the agent can use (omit = all tools available) |
| \`model\` | No | AI model preference (VS Code/JetBrains only) |
| \`mcp-servers\` | No | MCP server configurations for extended capabilities |

## Step 4 — Write the System Prompt

Below the frontmatter, write instructions in Markdown:

\`\`\`markdown
You are a testing specialist focused on improving code quality through
comprehensive testing. Your responsibilities:

- Analyze existing tests and identify coverage gaps
- Write unit tests, integration tests, and end-to-end tests
- Follow the project's existing test patterns and conventions
- Use the test framework already configured in the project
- Focus only on test files — avoid modifying production code
- Always include clear test descriptions

When writing tests:
1. Read the source file to understand the API
2. Check for existing tests to match the style
3. Write tests that cover happy paths, edge cases, and error cases
4. Run tests to verify they pass before finishing
\`\`\`

## Step 5 — Commit and Use

\`\`\`bash
git add .github/agents/test-writer.agent.md
git commit -m "feat: add test-writer custom agent"
git push
\`\`\`

In VS Code: Open Copilot Chat → click the agents dropdown → select **test-writer**.

On GitHub.com: Go to the agents tab → select **test-writer** from the dropdown.

---

## More Examples

### Code Reviewer Agent
\`\`\`yaml
---
name: code-reviewer
description: Reviews code for bugs, security issues, and best practices
tools: ["read", "search"]
---
You are a code review specialist. Review changes for:
- Logic errors and potential bugs
- Security vulnerabilities (injection, auth bypass, data exposure)
- Performance issues (N+1 queries, unnecessary allocations)
- Best practices for the language and framework in use

Only flag real issues. Never comment on style or formatting.
\`\`\`

### Documentation Agent
\`\`\`yaml
---
name: docs-writer
description: Writes and updates project documentation
tools: ["read", "edit", "search"]
---
You are a documentation specialist. Write clear, concise docs that:
- Explain the "why" not just the "what"
- Include code examples for every concept
- Use simple language (no jargon without definitions)
- Follow the project's existing documentation style
\`\`\`

### Security Auditor Agent (with MCP)
\`\`\`yaml
---
name: security-auditor
description: Audits code for security vulnerabilities and compliance issues
tools: ["read", "search", "security-scanner"]
mcp-servers:
  security-scanner:
    command: npx
    args: ["-y", "@example/security-mcp"]
---
You are a security specialist. Audit code for OWASP Top 10 vulnerabilities,
check dependency versions for known CVEs, and verify auth patterns.
\`\`\`

---

## Tips

- **Start simple** — create one agent, use it, then iterate. You can always add more tools and instructions later.
- **The \`description\` matters most** — Copilot reads it to decide when to suggest the agent. Be specific about what tasks the agent handles.
- **Omit \`tools\` to give full access** — only restrict tools when you want the agent to be read-only or limited.
- **Custom agents work everywhere** — VS Code, JetBrains, Eclipse, Xcode, GitHub.com, and the Copilot CLI.
- **Combine with CopilotForge skills** — your custom agents can reference skills in \`.github/skills/\` for even more specialized behavior.

## Learn More

- [Create custom agents](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/cloud-agent/create-custom-agents)
- [Test custom agents](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/cloud-agent/test-custom-agents)
- [Add skills to agents](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/cloud-agent/add-skills)
- [Custom agents configuration reference](https://docs.github.com/en/copilot/reference/custom-agents-configuration)
- [awesome-copilot agent examples](https://github.com/github/awesome-copilot/tree/main/agents)
`;

const COPILOT_AGENTS_EXAMPLE_MD = `---
name: project-expert
description: Answers questions about this project's architecture, conventions, and codebase
tools: ["read", "search"]
---

You are an expert on this project. When answering questions:

1. **Read first** — always look at the relevant source files before answering.
2. **Be specific** — reference exact file names, function names, and line numbers.
3. **Explain the why** — don't just describe what the code does, explain the design decisions.
4. **Use project conventions** — follow the patterns established in this codebase.

When asked about architecture:
- Start with the high-level overview (what the project does)
- Explain the directory structure and what lives where
- Describe how components interact
- Reference any documentation in \`docs/\` or \`README.md\`

When asked about a specific file or function:
- Read the file
- Explain its purpose and how it fits into the larger system
- Note any important dependencies or side effects
- Suggest related files the user might want to look at

Keep answers concise but thorough. Use code blocks for examples.
`;

module.exports = {
  FORGE_MD,
  PLANNER_AGENT_MD,
  DECISIONS_MD,
  PATTERNS_MD,
  PREFERENCES_MD,
  HELLO_WORLD_TS,
  HELLO_WORLD_PY,
  TASK_LOOP_TS,
  TASK_LOOP_PY,
  IMPLEMENTATION_PLAN_MD,
  GETTING_STARTED_MD,
  COPILOT_STUDIO_GUIDE_MD,
  COPILOT_STUDIO_AGENT_YAML,
  CODE_APPS_GUIDE_MD,
  CODE_APPS_SETUP_TS,
  COPILOT_AGENTS_GUIDE_MD,
  COPILOT_AGENTS_EXAMPLE_MD,
};
